-- MySQL Script generated by MySQL Workbench
-- Mon Aug 31 14:32:09 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`padrao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`padrao` (
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `role_id` BIGINT NOT NULL,
  `user_name` VARCHAR(40) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password_hash` VARCHAR(254) NOT NULL,
  `full_name` VARCHAR(126) NOT NULL,
  `bio` VARCHAR(100) NULL,
  `avatar_path` VARCHAR(254) NULL,
  `is_active` TINYINT(1) NOT NULL,
  `is_verified` TINYINT(1) NOT NULL,
  `last_login_at` TIMESTAMP NULL,
  `is_public` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `name` ENUM('SUPER', 'ADMIN', 'USER') NOT NULL,
  `description` VARCHAR(20) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `role_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  INDEX `role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` BIGINT NOT NULL,
  `title` VARCHAR(40) NOT NULL,
  `description` VARCHAR(512) NULL,
  `cover_image` VARCHAR(254) NULL,
  `category` VARCHAR(45) NOT NULL,
  `difficulty` TINYINT(4) NULL,
  `is_public` TINYINT(1) NULL,
  `total_students` BIGINT NOT NULL,
  `pined` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_c`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`module` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `course_id` BIGINT NOT NULL,
  `title` VARCHAR(40) NOT NULL,
  `description` VARCHAR(60) NULL,
  `order_position` SMALLINT NOT NULL,
  `estimated_duration` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lesson` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `title` VARCHAR(30) NOT NULL,
  `module_id` BIGINT NOT NULL,
  `estimated_duration` TIME NOT NULL,
  `order_position` SMALLINT NOT NULL,
  `description` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_module1_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_lesson_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES `mydb`.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`youtube_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`youtube_index` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `lesson_id` BIGINT NOT NULL,
  `url` VARCHAR(126) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_youtube_index_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_youtube_index_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`repetition_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repetition_note` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `front_text` TEXT NULL,
  `back_text` TEXT NULL,
  `front_audio_path` VARCHAR(126) NULL,
  `back_audio_path` VARCHAR(126) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`repetition_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repetition_card` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `title` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `repetition_note_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repetition_card_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_repetition_card_repetition_note1_idx` (`repetition_note_id` ASC) VISIBLE,
  CONSTRAINT `fk_repetition_card_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repetition_card_repetition_note1`
    FOREIGN KEY (`repetition_note_id`)
    REFERENCES `mydb`.`repetition_note` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`repetition_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repetition_schedule` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `repetition_card_id` BIGINT NOT NULL,
  `ease_factor` DECIMAL NOT NULL,
  `interval_days` INT NOT NULL,
  `last_review_at` DATETIME NULL,
  `next_review_at` DATETIME NOT NULL,
  `status` ENUM('REVIEWING', 'MASTERED', 'LEARNING', 'NEW') NOT NULL,
  `repetitions` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repetition_schedule_repetition_card1_idx` (`repetition_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_repetition_schedule_repetition_card1`
    FOREIGN KEY (`repetition_card_id`)
    REFERENCES `mydb`.`repetition_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`repetition_hystory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repetition_hystory` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `repetition_card_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repetition_hystory_repetition_card1_idx` (`repetition_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_repetition_hystory_repetition_card1`
    FOREIGN KEY (`repetition_card_id`)
    REFERENCES `mydb`.`repetition_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`shared_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shared_course` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `course_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shared_course_course1_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_shared_course_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_shared_course_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shared_course_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`course_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_comment` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `text` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `course_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_course_comment_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_comment_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` BIGINT NOT NULL,
  `subscription_id` BIGINT NOT NULL,
  `amount` INT NOT NULL,
  `paid_at` TIMESTAMP NOT NULL,
  `metadata` JSON NOT NULL,
  `payment_method` ENUM('PIX', 'CREDIT_CARD') NOT NULL,
  `gateway_transaction_id` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `gateway` ENUM('MERCADO_PAGO', 'STRIPE') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_transaction_subscription1_idx` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_subscription1`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `mydb`.`subscription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`defaut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`defaut` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`text` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `lesson_id` BIGINT NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_text_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_text_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`note` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` BIGINT NOT NULL,
  `texto` TEXT NOT NULL,
  `color` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_note_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `title` VARCHAR(25) NOT NULL,
  `content` VARCHAR(15) NOT NULL,
  `color` VARCHAR(10) NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tag_repetition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag_repetition` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `tag_id` BIGINT NOT NULL,
  `repetition_card_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_defaut_1_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_defaut_1_repetition_card1_idx` (`repetition_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_defaut_1_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_defaut_1_repetition_card1`
    FOREIGN KEY (`repetition_card_id`)
    REFERENCES `mydb`.`repetition_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tag_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag_course` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `tag_id` BIGINT NOT NULL,
  `course_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_course_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_tag_course_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_course_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_course_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tag_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag_module` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `tag_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_module_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_tag_module_module1_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_module_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_module_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES `mydb`.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tag_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag_lesson` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `tag_id` BIGINT NOT NULL,
  `lesson_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_lesson_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_tag_lesson_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_lesson_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_lesson_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pdf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pdf` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `lesson_id` BIGINT NOT NULL,
  `file_path` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_text_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_text_lesson10`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `lesson_id` BIGINT NOT NULL,
  `file_path` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_text_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_text_lesson100`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tag_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag_note` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `tag_id` BIGINT NOT NULL,
  `note_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_lesson_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_tag_note_note1_idx` (`note_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_lesson_tag10`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_note_note1`
    FOREIGN KEY (`note_id`)
    REFERENCES `mydb`.`note` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`repetition_mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repetition_mark` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `title` VARCHAR(45) NOT NULL,
  `lesson_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repetition_mark_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_repetition_mark_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`repetition_note_mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repetition_note_mark` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `front_text` TEXT NULL,
  `back_text` TEXT NULL,
  `front_audio_path` VARCHAR(126) NULL,
  `back_audio_path` VARCHAR(126) NULL,
  `repetition_mark_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repetition_note_mark_repetition_mark1_idx` (`repetition_mark_id` ASC) VISIBLE,
  CONSTRAINT `fk_repetition_note_mark_repetition_mark1`
    FOREIGN KEY (`repetition_mark_id`)
    REFERENCES `mydb`.`repetition_mark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
