-- MySQL Script generated by MySQL Workbench
-- Mon Aug 31 15:01:00 2026
-- Model: New Model    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SSO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SSO` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `SSO`;

-- -----------------------------------------------------
-- Table `SSO`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_name` VARCHAR(40) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password_hash` VARCHAR(254) NOT NULL,
  `full_name` VARCHAR(126) NOT NULL,
  `bio` VARCHAR(100) NULL,
  `avatar_path` VARCHAR(254) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` ENUM('SUPER', 'ADMIN', 'USER') NOT NULL,
  `description` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `role_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_role_UNIQUE` (`user_id` ASC, `role_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `SSO`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `title` VARCHAR(40) NOT NULL,
  `description` VARCHAR(512) NULL,
  `cover_image` VARCHAR(254) NULL,
  `category` VARCHAR(45) NOT NULL,
  `difficulty` TINYINT(4) NULL,
  `is_public` TINYINT(1) NOT NULL DEFAULT 1,
  `is_pinned` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `category_idx` (`category` ASC),
  CONSTRAINT `fk_course_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`module` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `course_id` BIGINT NOT NULL,
  `title` VARCHAR(40) NOT NULL,
  `description` VARCHAR(60) NULL,
  `order_position` SMALLINT NOT NULL,
  `estimated_duration` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_idx` (`course_id` ASC),
  UNIQUE INDEX `course_order_UNIQUE` (`course_id` ASC, `order_position` ASC),
  CONSTRAINT `fk_module_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `SSO`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`lesson` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(30) NOT NULL,
  `module_id` BIGINT NOT NULL,
  `estimated_duration` TIME NOT NULL,
  `order_position` SMALLINT NOT NULL,
  `description` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `module_idx` (`module_id` ASC),
  UNIQUE INDEX `module_order_UNIQUE` (`module_id` ASC, `order_position` ASC),
  CONSTRAINT `fk_lesson_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `SSO`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`youtube_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`youtube_index` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lesson_id` BIGINT NOT NULL,
  `url` VARCHAR(126) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lesson_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_youtube_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SSO`.`lesson` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`text` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lesson_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lesson_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_text_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SSO`.`lesson` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`pdf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`pdf` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lesson_id` BIGINT NOT NULL,
  `file_path` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lesson_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_pdf_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SSO`.`lesson` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lesson_id` BIGINT NOT NULL,
  `file_path` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lesson_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_video_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SSO`.`lesson` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`repetition_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`repetition_note` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `front_text` TEXT NULL,
  `back_text` TEXT NULL,
  `front_audio_path` VARCHAR(126) NULL,
  `back_audio_path` VARCHAR(126) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`repetition_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`repetition_card` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `repetition_note_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `repetition_note_idx` (`repetition_note_id` ASC),
  CONSTRAINT `fk_repetition_card_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_repetition_card_note`
    FOREIGN KEY (`repetition_note_id`)
    REFERENCES `SSO`.`repetition_note` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`repetition_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`repetition_schedule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `repetition_card_id` BIGINT NOT NULL,
  `ease_factor` DECIMAL(5,2) NOT NULL DEFAULT 2.50,
  `interval_days` INT NOT NULL DEFAULT 1,
  `last_review_at` DATETIME NULL,
  `next_review_at` DATETIME NOT NULL,
  `status` ENUM('REVIEWING', 'MASTERED', 'LEARNING', 'NEW') NOT NULL DEFAULT 'NEW',
  `repetitions` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `repetition_card_idx` (`repetition_card_id` ASC),
  INDEX `next_review_idx` (`next_review_at` ASC),
  CONSTRAINT `fk_schedule_card`
    FOREIGN KEY (`repetition_card_id`)
    REFERENCES `SSO`.`repetition_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`repetition_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`repetition_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `repetition_card_id` BIGINT NOT NULL,
  `review_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quality_rating` TINYINT NOT NULL,
  `response_time` INT NULL COMMENT 'Tempo de resposta em segundos',
  PRIMARY KEY (`id`),
  INDEX `repetition_card_idx` (`repetition_card_id` ASC),
  INDEX `review_date_idx` (`review_date` ASC),
  CONSTRAINT `fk_history_card`
    FOREIGN KEY (`repetition_card_id`)
    REFERENCES `SSO`.`repetition_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`shared_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`shared_course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `course_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `permission` ENUM('VIEW', 'EDIT', 'ADMIN') NOT NULL DEFAULT 'VIEW',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shared_course_UNIQUE` (`course_id` ASC, `user_id` ASC),
  INDEX `course_idx` (`course_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `fk_shared_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `SSO`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shared_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`course_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`course_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `text` VARCHAR(500) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `course_id` BIGINT NOT NULL,
  `parent_comment_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `course_idx` (`course_id` ASC),
  INDEX `parent_idx` (`parent_comment_id` ASC),
  CONSTRAINT `fk_comment_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `SSO`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_parent`
    FOREIGN KEY (`parent_comment_id`)
    REFERENCES `SSO`.`course_comment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`subscription_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`subscription_plan` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `duration_days` INT NOT NULL,
  `features` JSON NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`subscription` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `subscription_plan_id` BIGINT NOT NULL,
  `start_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_date` DATETIME NOT NULL,
  `status` ENUM('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  `auto_renew` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `plan_idx` (`subscription_plan_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `fk_subscription_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscription_plan`
    FOREIGN KEY (`subscription_plan_id`)
    REFERENCES `SSO`.`subscription_plan` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `subscription_id` BIGINT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `paid_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `metadata` JSON NULL,
  `payment_method` ENUM('PIX', 'CREDIT_CARD', 'BOLETO') NOT NULL,
  `gateway_transaction_id` VARCHAR(45) NOT NULL,
  `status` ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `gateway` ENUM('MERCADO_PAGO', 'STRIPE', 'PAYPAL') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `subscription_idx` (`subscription_id` ASC),
  UNIQUE INDEX `gateway_transaction_UNIQUE` (`gateway_transaction_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `fk_transaction_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_subscription`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `SSO`.`subscription` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`note` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `color` VARCHAR(10) NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `fk_note_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(25) NOT NULL,
  `color` VARCHAR(10) NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_tag_UNIQUE` (`user_id` ASC, `title` ASC),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `fk_tag_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`tag_repetition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`tag_repetition` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tag_id` BIGINT NOT NULL,
  `repetition_card_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_repetition_UNIQUE` (`tag_id` ASC, `repetition_card_id` ASC),
  INDEX `tag_idx` (`tag_id` ASC),
  INDEX `repetition_card_idx` (`repetition_card_id` ASC),
  CONSTRAINT `fk_tag_repetition_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `SSO`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tag_repetition_card`
    FOREIGN KEY (`repetition_card_id`)
    REFERENCES `SSO`.`repetition_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`tag_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`tag_course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tag_id` BIGINT NOT NULL,
  `course_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_course_UNIQUE` (`tag_id` ASC, `course_id` ASC),
  INDEX `tag_idx` (`tag_id` ASC),
  INDEX `course_idx` (`course_id` ASC),
  CONSTRAINT `fk_tag_course_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `SSO`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tag_course_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `SSO`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`tag_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`tag_module` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tag_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_module_UNIQUE` (`tag_id` ASC, `module_id` ASC),
  INDEX `tag_idx` (`tag_id` ASC),
  INDEX `module_idx` (`module_id` ASC),
  CONSTRAINT `fk_tag_module_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `SSO`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tag_module_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `SSO`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`tag_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`tag_lesson` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tag_id` BIGINT NOT NULL,
  `lesson_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_lesson_UNIQUE` (`tag_id` ASC, `lesson_id` ASC),
  INDEX `tag_idx` (`tag_id` ASC),
  INDEX `lesson_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_tag_lesson_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `SSO`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tag_lesson_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SSO`.`lesson` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`tag_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`tag_note` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tag_id` BIGINT NOT NULL,
  `note_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_note_UNIQUE` (`tag_id` ASC, `note_id` ASC),
  INDEX `tag_idx` (`tag_id` ASC),
  INDEX `note_idx` (`note_id` ASC),
  CONSTRAINT `fk_tag_note_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `SSO`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tag_note_note`
    FOREIGN KEY (`note_id`)
    REFERENCES `SSO`.`note` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`user_course_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`user_course_progress` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `course_id` BIGINT NOT NULL,
  `progress_percentage` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `last_accessed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_course_UNIQUE` (`user_id` ASC, `course_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `course_idx` (`course_id` ASC),
  CONSTRAINT `fk_progress_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_progress_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `SSO`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`user_lesson_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`user_lesson_progress` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `lesson_id` BIGINT NOT NULL,
  `is_completed` TINYINT(1) NOT NULL DEFAULT 0,
  `completed_at` DATETIME NULL,
  `last_accessed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_lesson_UNIQUE` (`user_id` ASC, `lesson_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `lesson_idx` (`lesson_id` ASC),
  CONSTRAINT `fk_lesson_progress_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lesson_progress_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SSO`.`lesson` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `entity_type` VARCHAR(45) NOT NULL,
  `entity_id` BIGINT NOT NULL,
  `old_values` JSON NULL,
  `new_values` JSON NULL,
  `ip_address` VARCHAR(45) NULL,
  `user_agent` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `entity_idx` (`entity_type` ASC, `entity_id` ASC),
  INDEX `created_at_idx` (`created_at` ASC),
  CONSTRAINT `fk_audit_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SSO`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSO`.`notification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `message` TEXT NOT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `read_at` DATETIME NULL,
  `metadata` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `is_read_idx` (`is_read` ASC),
  INDEX `created_at_idx` (`created_at` ASC),
  CONSTRAINT `fk_notification_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SSO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Inserção de dados iniciais
-- -----------------------------------------------------

-- Inserir roles padrão
INSERT INTO `SSO`.`role` (`name`, `description`) VALUES 
  ('SUPER', 'Super Administrador'),
  ('ADMIN', 'Administrador'),
  ('USER', 'Usuário Comum');

-- Inserir planos de assinatura padrão
INSERT INTO `SSO`.`subscription_plan` (`name`, `description`, `price`, `duration_days`, `features`) VALUES 
  ('FREE', 'Plano Gratuito', 0.00, 9999, '{"max_courses": 3, "max_repetition_cards": 50, "has_ads": true}'),
  ('PREMIUM', 'Plano Premium', 29.90, 30, '{"max_courses": 999, "max_repetition_cards": 999, "has_ads": false, "priority_support": true}'),
  ('PRO', 'Plano Profissional', 59.90, 30, '{"max_courses": 999, "max_repetition_cards": 999, "has_ads": false, "priority_support": true, "advanced_analytics": true}');

-- Criar usuário admin padrão (senha: admin123)
-- NOTA: Esta é uma hash bcrypt para demonstração. Troque a senha em produção!
INSERT INTO `SSO`.`user` (`user_name`, `email`, `password_hash`, `full_name`, `is_active`, `is_verified`) VALUES 
  ('admin', 'admin@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Administrador', 1, 1);

-- Atribuir role SUPER ao admin
INSERT INTO `SSO`.`user_role` (`role_id`, `user_id`) VALUES 
  (1, 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;